
# Configuración de la base de datos MySQL
spring:
  datasource:
    # url: jdbc:sqlserver://192.168.2.21:1433;databaseName=cuipo_dev;encrypt=true;trustServerCertificate=true;
    url: jdbc:mysql://127.0.0.1:3306/cuipo_dev
   
   
  


