# Puerto de la aplicación
server:
  port: 8001
  address: 0.0.0.0
  error:
    whitelabel:
      enabled: false  # Desactiva la página de error predeterminada
    include-message: always
    include-binding-errors: always
    path: /error  # Ruta de manejo de errores
  servlet:
    context-path: /  # Contexto de la aplicación

# Configuración de la aplicación
spring:
  # Permitir que Spring Boot lance una excepción cuando no encuentre un manejador
  mvc:
    throw-exception-if-no-handler-found: true

  # Configuración de Thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false  # Habilitar el caché en producción (puedes cambiarlo a 'true' en producción)

  # Configuración de correo electrónico
  mail:
    host: smtp.gmail.com
    port: 587
    username: jerssonovalle2@gmail.com
    password: egyw cias mgpd owgl
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  application:
    name: baseapp
  profiles:
    active: dev  # Cambia esto según el entorno: dev, qa, prod

  # Configuración de la base de datos MySQL
  datasource:
    username: sa
    password: Tecs2024*
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    show-sql: false
  output:
    ansi:
      enabled: always

  # Configuración de la seguridad de la aplicación
  security:
    user:
      name: user
      password: $2a$12$od1exy/dPLCsL3yxbJeFcO/AxDCKyYVBjl/bGB.7GgM3aGOWeWc.q

  # Clave secreta JWT
jwt:
  secret:
    key: "U6w3yjuQRNWNRG3IaajKZY8nyMPiu+wFLpj/7evdNEc="

# Configuración de la consola de la base de datos
logging:
  level:
    "[org.hibernate.SQL]": debug
    org.springframework.web.servlet.view: DEBUG
    org.thymeleaf: DEBUG

# Configuración imágenes
web:
  resources:
    static-locations: classpath:/static/,classpath:/public/

# Configuración de Swagger OpenAPI
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
    operationsSorter: method
    tagsSorter: alpha
    disable-swagger-default-url: true


