# Configuración del servidor 
server:
  port: 8001
  address: 0.0.0.0

# Configuración de la aplicación 
spring:
  application:
    name: baseapp
  # Entorno activo: dev, qa, prod
  profiles:
    active: dev 
  datasource:
    username: sa
    password: Tecs2024*
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    open-in-view: false
  output:
    ansi:
      enabled: always
  # Configuración Seguridad de la aplicación
  security:
    user:
     name: user
     password: $2a$12$od1exy/dPLCsL3yxbJeFcO/AxDCKyYVBjl/bGB.7GgM3aGOWeWc.q
# Clave secreta para JWT
jwt:
   secret:
    key: "U6w3yjuQRNWNRG3IaajKZY8nyMPiu+wFLpj/7evdNEc="  
# Configuración del logging
logging:
  level:
       "[org.hibernate.SQL]": debug


    
