#puerto de la aplicacion 
server:
  port: 8000
  address: 0.0.0.0

# Configuracion  de  la aplicacion  
spring:
  application:
    name: baseapp
  profiles:
    active: dev  # Cambia esto según el entorno: dev, qa, prod
  #Configuración de la base de datos MySQL
  datasource:
    username: sa
    password: Tecs2024*
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    show-sql: false
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  # Configuración de la seguridad de la aplicación
  security:
    enabled: false
    user:
     name: user
     password: $2a$12$od1exy/dPLCsL3yxbJeFcO/AxDCKyYVBjl/bGB.7GgM3aGOWeWc.q
  # Clave secreta JWT
jwt:
   secret:
    key: "U6w3yjuQRNWNRG3IaajKZY8nyMPiu+wFLpj/7evdNEc="  
  # Configuración de la consola de la base de datos
logging:
  level:
       "[org.hibernate.SQL]": debug


    
