# Configuración del servidor
server:
  port: ${SERVER_PORT}
  address: ${SERVER_ADDRESS}

# Configuración de la aplicación
spring:
  application:
    name: baseapp
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  datasource:
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: ${DATASOURCE_URL}
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    show-sql: false
    hibernate:
      ddl-auto: none
    open-in-view: false
  output:
    ansi:
      enabled: always
  # Configuración Seguridad de la aplicación
security:
  enable: false
  user:
    name: ${SECURITY_USERNAME}
    password: ${SECURITY_PASSWORD}

# Clave secreta para JWT
jwt:
  secret:
    key: ${JWT_SECRET_KEY}

# Configuración del logging
logging:
  level:
    "[org.hibernate.SQL]": debug
