# Puerto de la aplicación
server:
  port: 8001
  address: 0.0.0.0

# Configuración de la aplicación
spring:
  # Configuración de correo electrónico
  mail:
    host: smtp.gmail.com
    port: 587
    username: jerssonovalle2@gmail.com
    password: egyw cias mgpd owgl
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  application:
    name: baseapp
  profiles:
    active: dev  # Cambia esto según el entorno: dev, qa, prod

  # Configuración de la base de datos MySQL
  spring:
  datasource:
    username: sa
    password: Tecs2024*
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    show-sql: false
  output:
    ansi:
      enabled: always

  # Configuración de la seguridad de la aplicación
  security:
    user:
      name: user
      password: $2a$12$od1exy/dPLCsL3yxbJeFcO/AxDCKyYVBjl/bGB.7GgM3aGOWeWc.q

  # Clave secreta JWT
jwt:
  secret:
    key: "U6w3yjuQRNWNRG3IaajKZY8nyMPiu+wFLpj/7evdNEc="

# Configuración de la consola de la base de datos
logging:
  level:
    "[org.hibernate.SQL]": debug

#Configuracion imagenes
web:
  resources:
    static-locations: classpath:/static/,classpath:/public/
# Configuración de Swagger OpenAPI
    springdoc:
      api-docs:
        enabled: true
        path: /v3/api-docs
      swagger-ui:
        enabled: true
        path: /swagger-ui
        operationsSorter: method
        tagsSorter: alpha
        disable-swagger-default-url: true


