# Configuración del servidor 
server:
  port: 8001
  address: 0.0.0.0

# Configuración de la aplicación 
spring:
  application:
    name: baseapp
  profiles:
    active: dev
    # Entorno activo: dev, qa, prod
  datasource:
    username: sa
    password: Tecs2024*
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://192.168.2.62:1433;databaseName=cuipo_dev;encrypt=false;trustServerCertificate=true;
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    show-sql: false
    hibernate:
      ddl-auto: none
    open-in-view: false
  output:
    ansi:
      enabled: always
  # Configuración Seguridad de la aplicación
  security:
    enable: false
    user:
      name: user
      password: $2a$12$od1exy/dPLCsL3yxbJeFcO/AxDCKyYVBjl/bGB.7GgM3aGOWeWc.q

# Clave secreta para JWT
jwt:
  secret:
    key: "U6w3yjuQRNWNRG3IaajKZY8nyMPiu+wFLpj/7evdNEc="

# Configuración del logging
logging:
  level:
    "[org.hibernate.SQL]": debug