# Configuración del servidor 
server:
  port: ${SERVER_PORT}
  address: ${SERVER_ADDRESS}

# Configuración de la aplicación 
spring:
  application:
    name: baseapp
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
    # Entorno activo: dev, qa, prod
  datasource:
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    open-in-view: false
  output:
    ansi:
      enabled: always
  # Configuración Seguridad de la aplicación
  security:
    user:
      name: ${SECURITY_USERNAME}
      password: ${SECURITY_USERPASSWORD}

# Clave secreta para JWT
jwt:
  secret:
    key: ${JWT_SECRET_KEY}

# Configuración del logging
logging:
  level:
    "[org.hibernate.SQL]": debug
