name: Deploy to Local Server

on:
  push:
    branches:
      - dev-santiago # Cambia esto a la rama que activará el despliegue

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and Package Backend
        run: mvn clean install -DskipTests

      - name: Create Deployment Package
        run: |
          mkdir deploy_package
          cp .env deploy_package/
          cp target/*.jar deploy_package/
          cp Dockerfile deploy_package/
          tar -czvf t302-backend.tar -C deploy_package .

      - name: Transfer Package to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Para usar contraseña (menos seguro):
          # password: ${{ secrets.SSH_PASSWORD }}
          source: t302-backend.tar
          target: /home/${{ secrets.SSH_USER }}/t-302

      - name: Deploy to Docker on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Para usar contraseña (menos seguro)::
          # password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/${{ secrets.SSH_USER }}/t-302
            tar -xzvf cuipo-backend.tar
            docker build -t t302-backend:1.0 .
            docker stop t302-backend || true
            docker rm t302-backend || true
            docker run -d --name t302-backend -p 8005:8005 t302-backend:1.0
            echo "Deployment successful!"